# Generated by Django 5.1 on 2024-08-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_order_total_price_remove_product_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordered_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_quan", models.PositiveIntegerField()),
                ("ordered_price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.order"
                    ),
                ),
                (
                    "ordered_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.product"
                    ),
                ),
            ],
        ),
    ]
