# Generated by Django 5.1 on 2024-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_ordereditems2_delete_ordereditems"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordereditems2",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Order Placed"),
                    ("warehouse", "Left Warehouse"),
                    ("on_the_way", "On the Way"),
                    ("delivered", "Delivered"),
                ],
                default="ordered",
                max_length=20,
            ),
        ),
    ]
